config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  root 'posts#index'

  get 'static_pages/about'

  get 'static_pages/contact'

  post 'static_pages/thank_you'

  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts do
  	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
    user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :manage, User, id: user.id
        can :read, Post
      end
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :name, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence:true
  has_many :comments, dependent: :destroy
  acts_as_taggable
  has_attached_file :image, 
    styles: { large: "900x675>", thumb: "100x100>" }, 
    default_url: "/images/:style/missing.png",
    storage: :s3

  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def self.search(search_term)
    if Rails.env.production?
      Post.where("title ilike ?", "%#{search_term}%")
    else
      Post.where("title LIKE ?", "%#{search_term}%")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  require 'will_paginate/array'

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, alert: exception.message
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was created successfully.'}
        format.json {render :show, status: :created, location: @post }
      else
        format.html { redirect_to @post, alert: 'Comment was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    post = @comment.post
    @comment.destroy
    redirect_to post, notice: 'Comment was deleted.'
  end

  private

    def comment_params
      params.require(:comment).permit(:name, :body)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
 
  def index
    @posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page: 6)
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 6)
    end
    if params[:q]
      search_term = params[:q]
      @posts = Post.search(search_term).paginate(page: params[:page], per_page: 6)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :subtitle, :tag_list)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    ActionMailer::Base.mail(from: @email, to:'malin.ekelund@gmail.com', subject: "A new contact message from #{@name}", body: @message).deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Movelikeaswift</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz|Dosis|Acme|Titillium Web|Amaranth|Roboto|Josefin+Sans|Open+Sans|Open+Sans+Condensed:300" rel="stylesheet">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>

  <div class="page-wrap">

    <%= render 'shared/navigation_bar' %>

    <%= render 'shared/alerts' %>

    <%= yield %>

  </div><!-- end page-wrap -->

    <%= render 'shared/footer' %>

</body>
</html>

app/views/posts/_comments.html.erb
<div class="post-comments">
  <% @comments.each do |comment| %>
    <div class="row">
      <hr>
      <p><%= comment.name %> <small><em> <%= "#{time_ago_in_words(comment.created_at)} ago" %></em> </small>
        <% if signed_in? && current_user.admin? %>
        <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, post_comment_path(comment.post, comment), method: :delete, data: {confirm: 'Are you sure?' } %>
      <% end %></p>
      <p><%= comment.body %></p>
    </div>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, html: { multipart: true }) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_area :subtitle, id: :post_subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :tag_list, 'Tags (separated by commas)' %>
    <%= form.text_field :tag_list %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_new_comment.html.erb
<h4>You are welcome to leave a comment</h4>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.text_area(:body, class: "comment-form text") %>
  </p>
  <p>
    <%= f.text_field(:name, placeholder: "*Name", class: "comment-form name") %>
  </p>
  <p>
    <%= f.submit("Submit", class: "btn btn-default") %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div class="container-fluid edit-page">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |

<%= link_to 'Back', posts_path %>

<%= link_to 'Edit', edit_post_path(@post) %>

<%= link_to 'Destroy', @post, method: :delete, data: {confirm: 'Are you sure?' } %>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
  <div class="jumbotron" id="index-page-jumbotron">
    <div class="container welcome-text">
      <h2>Welcome! So nice you have you here.  This is a blog<br>about changing direction in life. My longing for<br>connection, happiness and fulfillment.</h2>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-left col-sm-12 col-md-9 col-lg-9 post-column">
    
    <% @posts.each do |post| %>
      <div class="col-sm-12 col-md-12 col-lg-6">
        <div class="post-title">
          <h2><%= post.title %></h2>
        </div>
        <%= image_tag(post.image.url(:large), class:"img-responsive post-img") %>
        <div class="post-subtitle">
          <p><%= post.subtitle %></p>
        </div>
        <div class="column date-and-button">
          <div class="post-published-at">
            <p><%= post.created_at.strftime("%B %d %Y") %></p>
          </div>
          <div class="button button-show-post">
            <%= link_to 'Read more', post, class: "btn btn-default" %>
          </div>
        </div>
      </div><!-- end col-sm-12 col-md-12 col-lg-6 -->
    <% end %>

    <div class="flickr_pagination">
      <% unless @posts.empty? %>
        <%= will_paginate @posts %>
      <% end %>
    </div>

  </div><!-- end row col-sm-12 col-md-9 col-lg-9-->

  <div class="row-right col-sm-12 col-md-3 col-lg-3">
    <div class="about-me">
      <h2>About me</h2>
        <p>This is my place to tell some stories. Stories from my current life and stories from the journey I have been on since I left my previous career in Sweden.<br><br>To read more about swifts and why they inspire me so much please visit the <%= link_to "about ", static_pages_about_path %>page.</p>
    </div>
    <div class="categories">
      <h2>Categories</h2>
      <div class="tag_cloud">
        <% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
          <div class="btn btn-info">
            <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          </div>
        <% end %>
      </div>
    </div>
  </div><!-- end row col-sm-12 col-md-3 col-lg-3-->

</div><!-- container-fluid -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container-fluid">
  <div class="jumbotron" id="show-page-jumbotron">
    <div class="container show-page-text">
      <h1>Enjoy every moment</h1>
    </div>
  </div>
</div><!-- end container-fluid -->
<div class="container">
  <div class="col-sm-12 col-md-9 col-lg-9" id="show-post" data-post-id="<%=@post.id %>">
    <div class="post-title">
      <h2><%= @post.title %></h2>
    </div>
    <div class="post-published-at-show">
      <p><%= @post.created_at.strftime("%B %d %Y") %></p>
    </div>
    <%= image_tag(@post.image.url(:large), class: "img-responsive img-show") %>
    <div class="post-body">
      <p><%= simple_format(@post.body) %></p>
    </div>
    <div class="tag-link">
      <p>Categories: <%= raw(@post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></p>
    </div>
    <div class="button button-back-post">
      <%= link_to 'Back', posts_path, class: "btn btn-default" %>
    </div>
  </div><!-- end col-sm-12 col-md-9 col-lg-9 -->
  <div class="col-sm-12 col-md-3 col-lg-3">
    <div class="comments">
      <h2>Comments</h2>
      <%= render 'new_comment' %>
      <%= render 'comments' %>
    </div>
  </div><!-- end col-sm-12 col-md-3 col-lg-3 -->
</div><!-- end container -->

app/views/shared/_alerts.html.erb
<% if notice %>
    <p id="notice" class="alert alert-warning" role="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p id="alert" class="alert alert-warning" role="alert"><%= alert %></p>
  <% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer-icons">
    <a href="https://www.instagram.com/movelikeaswift/" target="_blank" class="fa fa-instagram fa-3x"></a>
    <a href="https://www.pinterest.se/ekemal/" target="_blank" class="fa fa-pinterest fa-3x"></a>
  </div>
  <p>&copy; movelikeaswift 2018</p>
</footer>

app/views/shared/_navigation_bar.html.erb
<!-- NAVIGATION BAR -->
  
  <nav class="navbar navbar-inverse navbar-fixed-top"  role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toogle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <div><%= image_tag("logonew.png", size: "249x48") %></div>
          </a>
        </div><!-- end navbar-header -->

        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", posts_path %></li>
            <li><%= link_to "About", static_pages_about_path %></li>
            <li><%= link_to "Contact", static_pages_contact_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="search-form">
              <%= form_with(url: posts_path, method: 'get', local:true) do |form| %>
                <%= form.text_field :q, id: 'q', value: params[:q], placeholder: "Search", class: "search-field" %>
                <%= button_tag "", type: 'submit', class: "btn submit glyphicon glyphicon-search search-button" %>
              <% end %>
            </li>
            <li class="login">
              <% if user_signed_in? %>
                <%= link_to("Log out", destroy_user_session_path, method: :get, class: "btn btn-default button-login") %>
              <% else %>
                <%= link_to("Log in", new_user_session_path, class: "btn btn-default button-login") %>
              <% end %>
            </li>
          </ul>
        </div><!-- end navbar-collapse collapse" -->
      </div><!-- end container-fluid -->
    
    </nav><!-- END NAVIGATION BAR -->

app/views/static_pages/about.html.erb
<div class="container-fluid about-page">
  <div class="row">
    <%=image_tag("swifts.png", class: "col-xs-12 col-sm-12 col-md-4 col-lg-4 img-responsive img-swifts") %>
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 col-md-offset-3 col-lg-offset-3 about-text">
      <h2>I have been thinking about starting a blog for a long time. But then I have been feeling doubt, do I really want to expose myself like this? But I really like to write, and I like pictures, so I'm doing it mostly for myself. I think I'm going to enjoy it. To put things out there. And that's a great starting point for me, joy.<br><br>I have recently learned to build websites so I took this opportunity and built this blog. It's designed and coded from scratch by me.</h2>
    </div>
  </div>
  <div class="row">
    <div class=" col-xs-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2 about-swifts">
      <h2>Since my father died birds are very special to me. My father loved birds, they were one of his passions in life. I don’t really know much about birds but some of his favorite birds I really feel a strong connection to, they bring me closer to him. As a child he taught me about birds and that’s just one of the many many things I'm so grateful for. My father gave me so much.<br><br><strong>Common swifts</strong> were one of his favorite birds. A swift is also engraved on his tombstone. It’s truly a very inspiring bird. No other bird spends as much of its life in flight, some individuals can go 10 months (!!!) without landing. They spend their lives in the air, living on the insects they catch in flight. They even mate and sleep on the wing. Like many birds they are migratory and this is in itself very inspiring, knowing exactly in which direction to fly, they always get to their destination, they have this inner compass, this wisdom.<br><br>For these reasons I find swifts truly inspiring. They really represent freedom to me. Freedom with a direction, which is the ideal state of being for me. 
      </h2>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<div class="container-fluid contact-page">

<%= flash[:notice] %>

<%= form_with(url:"/static_pages/thank_you", method: "post", local: true) do |form| %>
  <div class="container-fluid col-xs-12 col-sm-8 col-md-4 col-lg-4 col-md-offset-2 col-lg-offset-2">
    <h2>You are very welcome to contact me</h2>
    <div class="form-group">
      <%= form.label(:name, "Name*") %>
      <%= form.text_field :name, class: "form-control", placeholder: "Enter name", required: true %>
    </div>
    <div class="form-group">
      <%= form.label(:email, "Email*") %>
      <%= form.text_field :email, class: "form-control", placeholder: "Enter email", required: true %>
    </div>
    <div class="form-group">
      <%= form.label(:message, "Message*") %>
      <%= form.text_area :message, class: "form-control", placeholder: "Enter message", rows: 5, required: true %>
    </div>
      <%= form.submit "Send", class: "form_label btn btn-default button-contactpage" %>
  </div><!-- end container-fluid -->
  
<% end %>

</div>

app/views/static_pages/thank_you.html.erb
<div class="column col-xs-12 col-sm-12 col-md-8 col-lg-6 col-md-offset-2 col-lg-offset-3">
  <div class="row message">
    <h3>Thank you. I have received your message and will respond as soon as possible.<br><br>Have a beautiful day.</h3>
  </div>

  <h3 class="link"> <%= link_to "Back to home", root_url %></h3>

</div><!-- end column -->

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>